@startuml
  
package auth-provider.ts {
    class handleUserResponse{}
    class logout {}
    class getToken{}
    class register {}
    class login{}
    login -.-> handleUserResponse
    register -.-> handleUserResponse
}

package auth-context.tsx {
  class AuthProvider {
    + AuthProvider: ({children}) => <AuthContext.Provider />
  }
  class bootstrapUser {}
  note right
    Get token if exist in local storage
    Return the user according to the token

    Use useMount to init in every refresh
  end note
  AuthProvider -.-> login
  AuthProvider -.-> register
  AuthProvider -.-> logout

}



@enduml